name: Backend deployment

on:
  push:
    branches: [ main ]
  pull_request_review:
    types: [submitted]
    branches: ['master']
    paths: [' **path/**']

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker logout
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker build
        run: |
          docker build --tag tourneys_img .

      - name: docker tag
        run: |
          docker image tag tourneys_img nonce1/tourneys-bot

      - name: docker push
        run: |
          docker push nonce1/tourneys-bot

  heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, push and release the docker container to heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: worker

  gh-registry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker gh container login
      run: |
        echo $PAT | docker login ghcr.io -u Existential-nonce --password-stdin
      env:
        PAT: ${{ secrets.PAT }}

    - name : Build gh container
      run: |
        docker build . --tag ghcr.io/existential-nonce/tourneys-bot:latest

    - name : Push gh container
      run: |
        docker push ghcr.io/existential-nonce/tourneys-bot:latest